version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  compose-and-upload:
    lang: python3-flask
    handler: ./compose-and-upload
    image: compose-and-upload:latest
    labels:
      "com.openfaas.scale.max": "1"