version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  compose-post:
    lang: python3-flask
    handler: ./compose-post
    image: compose-post:latest
    labels:
      "com.openfaas.scale.max": "1"