---
apiVersion: v1
kind: Service
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: socialnetwork-db
    app-name: home-timeline-redis
  namespace: socialnetwork-db
spec:
  ports:
  - port: 6379
  selector:
    death-star-project: socialnetwork-db
    app-name: home-timeline-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-timeline-redis
  labels:
    death-star-project: socialnetwork-db
    app-name: home-timeline-redis
  namespace: socialnetwork-db
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: socialnetwork-db
      app-name: home-timeline-redis
  template:
    metadata:
      labels: 
        death-star-project: socialnetwork-db
        app-name: home-timeline-redis
      name: home-timeline-redis
    spec:
      containers:
      - name: home-timeline-redis
        image: redis
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

