version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:31112
functions:
  compose-review:
    lang: python3-flask
    handler: ./compose-review
    image: compose-review:latest
    labels:
      "com.openfaas.scale.max": "1"
