---
apiVersion: v1
kind: Service
metadata:
  name: cast-info-mongodb
  labels:
    death-star-project: movie-reviewing
    app-name: cast-info-mongodb
  namespace: movie-reviewing
spec:
  ports:
  - port: 27017
  selector:
    death-star-project: movie-reviewing
    app-name: cast-info-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-info-mongodb
  labels:
    death-star-project: movie-reviewing
    app-name: cast-info-mongodb
  namespace: movie-reviewing
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: movie-reviewing
      app-name: cast-info-mongodb
  template:
    metadata:
      labels: 
        death-star-project: movie-reviewing
        app-name: cast-info-mongodb
      name: cast-info-mongodb
    spec:
      containers:
      - name: cast-info-mongodb
        image: mongo
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

