---
apiVersion: v1
kind: Service
metadata:
  name: movie-id-memcached
  labels:
    death-star-project: movie-reviewing
    app-name: movie-id-memcached
  namespace: movie-reviewing
spec:
  ports:
  - port: 11211
  selector:
    death-star-project: movie-reviewing
    app-name: movie-id-memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-id-memcached
  labels:
    death-star-project: movie-reviewing
    app-name: movie-id-memcached
  namespace: movie-reviewing
spec:
  replicas: 1
  selector:
    matchLabels:
      death-star-project: movie-reviewing
      app-name: movie-id-memcached
  template:
    metadata:
      labels: 
        death-star-project: movie-reviewing
        app-name: movie-id-memcached
      name: movie-id-memcached
    spec:
      containers:
      - name: movie-id-memcached
        image: memcached
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

